---
- name: user module demo
  hosts: all
  become: true
  vars:
    myuser: "testuser"
    mypassword: "Password1"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ testuser }}"
        state: present
        password: "{{ Password2 | password_hash('sha512') }}"
