---
- name: Playbook to copy files
  become: true
  hosts: all

  tasks:

    - name: Copy file with owner and permissions
      copy:
        src: /etc/hosts
        dest: /etc/demo
        owner: root
        group: root
        mode: '0644'
