---
- hosts: all
  become: true
  tasks:
  - name: create user on remote host
    ansible.builtin.user:
      name: ansible_test
      password: ufHRwxpZVc3e
      shell: /bin/bash
      groups: "sudo"
