---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and make sure Vim, Curl Unzip and Mlocate are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - curl
        - unzip
        - mlocate
