- hosts: all
  become: true
  tasks:
  - name: disable upgrade php7.4
    dpkg_selections:
      name: mysql-server
      selection: hold

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
